version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - aws s3 sync --delete . "s3://www.telephant.co.za" --exclude "README.md" --exclude ".git/"  --exclude "buildspec.yml"
 post_build:
   commands:
     - echo "post_build step"